## google ##
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 980126786848-k8np1re3vq63spbsq4nqb18nnmljnbei.apps.googleusercontent.com
            client-secret: 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
          naver:
            client-id: ggd6FeYixo31mERxF_ZM
            client-password: H4QoBD9Dei
